num1=int(input("Enter the first number  : "))
num2=int(input("Enter the second number : "))
total=num1+num2
print(total)
print(total*2)
print(total/2)
print(total + 100)
print(total - 100)
print(total * 10)
print(total // 7)
print(total % 7)
